"""empty message

Revision ID: 4f6885a6400e
Revises: 6a7054db6e81
Create Date: 2022-05-08 11:39:23.639183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6885a6400e'
down_revision = '6a7054db6e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style', 'image')
    # ### end Alembic commands ###
