"""Add updated_date column and change the column's name, 'availability', to 'available'

Revision ID: 860c626bffad
Revises: f61ee860b470
Create Date: 2022-05-27 18:13:43.754944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860c626bffad'
down_revision = 'f61ee860b470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barber', sa.Column('available', sa.Boolean(), nullable=True))
    op.drop_column('barber', 'availability')
    op.add_column('user', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_date')
    op.add_column('barber', sa.Column('availability', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('barber', 'available')
    # ### end Alembic commands ###
