"""Add updated_date column and change the column's name, 'availability', to 'available'

Revision ID: bf67596f7b8b
Revises: 860c626bffad
Create Date: 2022-05-27 18:14:59.641600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf67596f7b8b'
down_revision = '860c626bffad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barber', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('barber', 'update_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barber', sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('barber', 'updated_date')
    # ### end Alembic commands ###
