"""Change Style id type to String

Revision ID: 1e44e70023ef
Revises: cada872c728b
Create Date: 2022-05-28 16:44:18.301982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e44e70023ef'
down_revision = 'cada872c728b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('ids', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style', 'ids')
    # ### end Alembic commands ###
