"""Drop style table

Revision ID: 31ee10aac357
Revises: f7c7f06bd78e
Create Date: 2022-05-29 20:20:11.476911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31ee10aac357'
down_revision = 'f7c7f06bd78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style')
    op.drop_table('barber_styles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber_styles',
    sa.Column('barber_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('style_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barber.id'], name='barber_styles_barber_id_fkey'),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], name='barber_styles_style_id_fkey'),
    sa.PrimaryKeyConstraint('barber_id', 'style_id', name='barber_styles_pkey')
    )
    op.create_table('style',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='style_pkey')
    )
    # ### end Alembic commands ###
