"""empty message

Revision ID: 366985d9e4a2
Revises: 5fe6819e26aa
Create Date: 2022-05-29 19:56:01.209898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366985d9e4a2'
down_revision = '5fe6819e26aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style', 'ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('ids', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
