"""Change the table Comments' name to Reviews

Revision ID: 9c8205b4dbe5
Revises: 264ce1398389
Create Date: 2022-05-25 20:17:22.325703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8205b4dbe5'
down_revision = '264ce1398389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.Text(), nullable=True))
    op.drop_column('reviews', 'Reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('Reviews', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
