"""empty message

Revision ID: cada872c728b
Revises: bf67596f7b8b
Create Date: 2022-05-28 11:05:48.978502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cada872c728b'
down_revision = 'bf67596f7b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('style', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style', 'updated_date')
    op.drop_column('style', 'created_date')
    # ### end Alembic commands ###
