"""empty message

Revision ID: cf31f8389860
Revises: 1e44e70023ef
Create Date: 2022-05-29 19:25:59.764054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf31f8389860'
down_revision = '1e44e70023ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('barber_styles_style_id_fkey', 'barber_styles', type_='foreignkey')
    op.create_foreign_key(None, 'barber_styles', 'style', ['style_id'], ['ids'])
    op.add_column('style', sa.Column('ids', sa.String(length=80), nullable=False))
    op.drop_column('style', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('style_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('style', 'ids')
    op.drop_constraint(None, 'barber_styles', type_='foreignkey')
    op.create_foreign_key('barber_styles_style_id_fkey', 'barber_styles', 'style', ['style_id'], ['id'])
    # ### end Alembic commands ###
