"""change style 2

Revision ID: f7c7f06bd78e
Revises: 366985d9e4a2
Create Date: 2022-05-29 20:06:08.340700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c7f06bd78e'
down_revision = '366985d9e4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('barber_styles_style_id_fkey', 'barber_styles', type_='foreignkey')
    op.add_column('style', sa.Column('ids', sa.String(length=80), nullable=False))
    op.create_foreign_key('barber_styles_style_id_fkey', 'barber_styles', 'style', ['style_id'], ['ids'])
    op.drop_column('style', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('style_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('style', 'ids')
    op.drop_constraint(None, 'barber_styles', type_='foreignkey')
    op.create_foreign_key('barber_styles_style_id_fkey', 'barber_styles', 'style', ['style_id'], ['id'])
    # ### end Alembic commands ###
