"""empty message

Revision ID: fa7f9295454d
Revises: 6aad87abdd83
Create Date: 2022-05-29 19:36:45.898256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7f9295454d'
down_revision = '6aad87abdd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style', sa.Column('ids', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style', 'ids')
    # ### end Alembic commands ###
